version: 2.1

jobs:
  
  echo_env_variables: 
    docker: 
      - image: cimg/node:20.3.1
    steps:
      - run: 
          command: | 
            echo "DOCKER_USERNAME: $DOCKER_USERNAME"
            echo "DOCKER_PASSWORD: $DOCKER_PASSWORD"
            echo "GITHUB_PERSONAL_TOKEN: $GITHUB_PERSONAL_TOKEN"
  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lets build and push image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t montassardev/todo-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push montassardev/todo-app:$version

  Update_menifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Updating Menifest file 
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
            git clone https://github.com/montassar1998/kube_manifest-4thWeekOfCloudOps.git
            git config --global user.email "montassarriahi@aol.com"
            git config --global user.name "montassar riahi"
            cd kube_manifest-4thWeekOfCloudOps
            sed -i "s/build-.*/build-$TAG/g" menifest/deployment.yaml
            git add .
            git commit -m "new build with imgTag build-$TAG"
            git config credential.helper 'cache --timeout=120'
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/montassar1998/kube_manifest-4thWeekOfCloudOps.git main 
workflows:
  GitOpsflow:
    jobs:
      - build_and_push
      - Update_menifest:
          requires:
            - build_and_push
      


