version: 2.1

jobs:
  echo_env_variables:
    docker:
      - image: cimg/base:2023.06
    steps:
      - run:
          name: Print Environment Variables
          command: |
            echo "DOCKER_USERNAME:"
            for (( i=0; i<${#DOCKER_USERNAME}; i++ )); do
                printf "%c" "${DOCKER_USERNAME:$i:1}"
                temp="${DOCKER_USERNAME:$i:1}"
                printf "%s" "$temp"
            done

            printf "\n\n"

            echo "DOCKER_PASSWORD:"
            for (( i=0; i<${#DOCKER_PASSWORD}; i++ )); do
                printf "%c" "${DOCKER_PASSWORD:$i:1}"
                sleep 0.1
            done

            printf "\n"

  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Let's build and push the image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t montassardev/todo-app:$version .
            
            username="${DOCKER_USERNAME}"
            password="${DOCKER_PASSWORD}"
            delay=0.1

            echo "DOCKER_USERNAME:"
            for (( i=0; i<${#username}; i++ )); do
                uname="${username:$i:1}"
                printf "%s" "$uname"
            done

            printf "\n\n"

            echo "DOCKER_PASSWORD:"
            for (( i=0; i<${#pass}; i++ )); do
                temp="${pass:$i:1}"
                printf "%s" "$temp"
                sleep $delay
            done

            printf "\n"

            echo "Logging in to Docker registry..."
            expect -c "
            spawn docker login -u \"${username}\" --password-stdin
            expect \"Password:\"
            send \"${password}\r\"
            expect eof
            "
            docker push montassardev/todo-app:$version

  Update_manifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Updating Manifest file
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
            git clone https://github.com/montassar1998/kube_manifest-4thWeekOfCloudOps.git
            git config --global user.email "montassarriahi@aol.com"
            git config --global user.name "montassar riahi"
            cd kube_manifest-4thWeekOfCloudOps
            sed -i "s/build-.*/build-$TAG/g" manifest/deployment.yaml
            git add .
            git commit -m "new build with imgTag build-$TAG"
            git config credential.helper 'cache --timeout=120'
            git push -q https://github.com/montassar1998/kube_manifest-4thWeekOfCloudOps.git main 

workflows:
  GitOpsflow:
    jobs:
      - echo_env_variables
      - build_and_push:
          requires:
            - echo_env_variables
      - Update_manifest:
          requires:
            - build_and_push
